# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vAods6bhSOpf5PF3bJhiZHEQKiDIF0Oz

##Import Libararies
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

analyst=pd.read_csv('/content/Data_Analyst_Take_Home.csv',sep=',')

"""##Summarize data

"""

analyst.head()

analyst.info()

"""##Data visualization"""

sns.pairplot(analyst)

orderid=analyst['CustomerId'].head(12)
RestaurantId=analyst['Date'].head(12)
 
# Figure Size
fig = plt.figure(figsize =(10, 7))
 
# Horizontal Bar Plot
plt.bar(orderid[0:10],RestaurantId[0:10])
 
# Show Plot
plt.show()